//! The teaching resources, embedded at compile time — the same
//! lockstep as the shipped system ([`crate::bootstrap`]): what this
//! build serves is what this build's suite tested. A skill is a
//! directory under the repo's `skills/`: its `SKILL.md`, served on the
//! MCP door as a resource and as a prompt, and its references, served
//! as sibling resources the SKILL.md names for the moment they are
//! needed (the Agent Skills layout: metadata, then the one page, then
//! files on demand). The normative artifacts, the `docs/` pages and
//! the engine's SQL guide under `vendor/` ride along as `doc://`
//! resources, because a connected agent has no checkout to read them
//! from — what an agent in this repository reads is what the door
//! serves. [`door_pages`] is the one list of them: the plane holds it,
//! the MCP door lists and reads its resources from it, and the
//! `pages()` read serves the same rows to a client that has the
//! statement tool and no resource reader.

/// One product skill: its directory name and its `SKILL.md`, verbatim
/// — frontmatter included, as an Agent Plugins host would read it.
pub struct Skill {
    pub name: &'static str,
    pub body: &'static str,
}

/// The product skills. The suite holds this table to the `skills/`
/// directory (`tests/suite/skills.rs`), so a skill added on disk
/// without a row here fails the build.
pub const SKILLS: [Skill; 4] = [
    Skill {
        name: "glossql",
        body: include_str!("../../../skills/glossql/SKILL.md"),
    },
    Skill {
        name: "glossql-metrics",
        body: include_str!("../../../skills/glossql-metrics/SKILL.md"),
    },
    Skill {
        name: "glossql-functions",
        body: include_str!("../../../skills/glossql-functions/SKILL.md"),
    },
    Skill {
        name: "glossql-apps",
        body: include_str!("../../../skills/glossql-apps/SKILL.md"),
    },
];

impl Skill {
    /// The resource URI — the `skill://<name>/SKILL.md` shape of
    /// skills-over-MCP (SEP-2640), without that proposal's extension
    /// machinery: a single-file skill needs a URI and a body, nothing
    /// more.
    pub fn uri(&self) -> String {
        format!("skill://{}/SKILL.md", self.name)
    }

    /// The frontmatter's `description:` line — the same line an Agent
    /// Plugins host lists a skill by.
    pub fn description(&self) -> &'static str {
        let mut in_frontmatter = false;
        for line in self.body.lines() {
            if line.trim() == "---" {
                if in_frontmatter {
                    break;
                }
                in_frontmatter = true;
                continue;
            }
            if in_frontmatter && let Some(rest) = line.strip_prefix("description:") {
                return rest.trim();
            }
        }
        ""
    }
}

/// A normative artifact the skills cite.
pub struct Doc {
    pub name: &'static str,
    pub description: &'static str,
    pub mime: &'static str,
    pub body: &'static str,
}

pub const DOCS: [Doc; 2] = [
    Doc {
        name: "SPEC.md",
        description: "The glossql language specification — the normative prose the \
                      skills cite by section.",
        mime: "text/markdown",
        body: include_str!("../../../SPEC.md"),
    },
    Doc {
        name: "grammar.ebnf",
        description: "The machine-readable glossql grammar.",
        mime: "text/plain",
        body: include_str!("../../../grammar.ebnf"),
    },
];

impl Doc {
    pub fn uri(&self) -> String {
        format!("doc://{}", self.name)
    }
}

/// One embedded page of a tree: its repo-relative path and its body,
/// verbatim. The tables are generated by `build.rs` from what is on
/// disk: `REFERENCES` is every `.md` under `skills/` other than a
/// `SKILL.md`, `PAGES` every `.md` under `docs/`, `VENDORED` every
/// `.md` under `vendor/` — DataFusion's SQL user guide at the tag the
/// lock resolves, refreshed by `vendor/datafusion/refresh.sh`.
pub struct Page {
    pub path: &'static str,
    pub body: &'static str,
}

include!(concat!(env!("OUT_DIR"), "/embedded.rs"));

impl Page {
    /// One rule for both trees: a skill's file is
    /// `skill://<name>/<path in the skill>`, the same root its
    /// `SKILL.md` has; a docs or vendored page is `doc://<repo path>`,
    /// the same root as `doc://SPEC.md`.
    pub fn uri(&self) -> String {
        match self.path.strip_prefix("skills/") {
            Some(rest) => format!("skill://{rest}"),
            None => format!("doc://{}", self.path),
        }
    }

    /// The page's first heading — what a listing shows beside the URI,
    /// so a reference's title says when to read it.
    pub fn title(&self) -> &'static str {
        first_heading(self.body).unwrap_or(self.path)
    }
}

/// A page's first `# ` heading.
fn first_heading(body: &str) -> Option<&str> {
    body.lines()
        .find_map(|l| l.strip_prefix("# "))
        .map(str::trim)
}

/// Every page of the binary, in the order every surface serves them:
/// the skills, the two normative artifacts, then the trees — a skill's
/// references after its SKILL.md, the docs pages, the engine's SQL
/// guide. A tree page is described by its first heading, which is what
/// tells a reader when the page is worth its tokens.
pub fn door_pages() -> std::sync::Arc<[glossql_session::DoorPage]> {
    use glossql_session::DoorPage;
    let mut out: Vec<DoorPage> = SKILLS
        .iter()
        .map(|s| DoorPage {
            uri: s.uri(),
            name: s.name.to_string(),
            title: first_heading(s.body).unwrap_or(s.name).to_string(),
            description: s.description().to_string(),
            mime: "text/markdown",
            body: s.body.to_string(),
        })
        .collect();
    out.extend(DOCS.iter().map(|d| DoorPage {
        uri: d.uri(),
        name: d.name.to_string(),
        title: d.description.to_string(),
        description: d.description.to_string(),
        mime: d.mime,
        body: d.body.to_string(),
    }));
    out.extend(
        REFERENCES
            .iter()
            .chain(PAGES.iter())
            .chain(VENDORED.iter())
            .map(|p| DoorPage {
                uri: p.uri(),
                name: p.path.to_string(),
                title: p.title().to_string(),
                description: p.title().to_string(),
                mime: "text/markdown",
                body: p.body.to_string(),
            }),
    );
    out.into()
}

/// The door's pages plus the ones built at boot — the function
/// listings — in one list, the boot pages last.
pub fn door_pages_with(
    extra: Vec<glossql_session::DoorPage>,
) -> std::sync::Arc<[glossql_session::DoorPage]> {
    let mut out: Vec<glossql_session::DoorPage> = door_pages().to_vec();
    out.extend(extra);
    out.into()
}
