[package]
name = "glossql-catalog"
version = "0.1.0"
edition.workspace = true

[lib]
name = "glossql_catalog"
path = "src/lib.rs"

[dependencies]
datafusion = { workspace = true }
iceberg = { workspace = true }
iceberg-catalog-sql = { workspace = true }
iceberg-datafusion = { workspace = true }
async-trait = "0.1"
futures = "0.3"
sqlx = { workspace = true }
uuid = { version = "1", features = ["v7"] }
thiserror = { workspace = true }
tokio = { workspace = true }

[dev-dependencies]
tempfile = "3"

[lints]
workspace = true
