[package]
name = "glossql-apps"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
glossql-glossary = { path = "../glossary" }
glossql-session = { path = "../session" }
datafusion = { workspace = true }
arrow-ipc = { workspace = true }
axum = { workspace = true }
futures.workspace = true
serde.workspace = true
serde_json = { workspace = true }
tera.workspace = true
tokio = { workspace = true }
toml.workspace = true

[dev-dependencies]
glossql-catalog = { path = "../catalog" }
glossql-parser = { path = "../parser" }
glossql-scripts = { path = "../scripts" }
tower.workspace = true
tempfile.workspace = true

[lints]
workspace = true
